import { JSONFilePreset } from 'lowdb/node';
import { Invite, Permission, User } from './types';

interface Data {
	permissions: Permission[];
	users: User[];
	invites: Invite[];
}

const defaultData: Data = {
	permissions: [
		'read_posts',
		'write_posts',
		'read_messages',
		'write_messages',
		'read_profile',
		'write_profile',
	],
	users: [
		{ id: '1', email: 'kenta@gmail.com', isVerified: true, hasInvite: false },
		{ id: '2', email: 'jordan@gmail.com', isVerified: true, hasInvite: false },
		{ id: '3', email: 'bob@gmail.com', isVerified: true, hasInvite: false },
		{ id: '4', email: 'emily@gmail.com', isVerified: true, hasInvite: false },
		{ id: '5', email: 'alex@gmail.com', isVerified: true, hasInvite: false },
		{ id: '6', email: 'sophia@gmail.com', isVerified: true, hasInvite: false },
		{ id: '7', email: 'liam@gmail.com', isVerified: true, hasInvite: false },
		{ id: '8', email: 'olivia@gmail.com', isVerified: true, hasInvite: false },
		{ id: '9', email: 'noah@gmail.com', isVerified: true, hasInvite: false },
		{ id: '10', email: 'ava@gmail.com', isVerified: true, hasInvite: false },
		{ id: '11', email: 'ethan@gmail.com', isVerified: true, hasInvite: false },
		{ id: '12', email: 'mia@gmail.com', isVerified: false, hasInvite: false },
		{ id: '13', email: 'mason@gmail.com', isVerified: false, hasInvite: false },
		{ id: '14', email: 'isabella@gmail.com', isVerified: false, hasInvite: false },
		{ id: '15', email: 'william@gmail.com', isVerified: false, hasInvite: false },
	],
	invites: [
		{
			id: '1UpVVyFeTPEvof5kH',
			fromUserId: '1',
			toUserId: '12',
			permissions: ['read_messages', 'write_messages', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-12T08:34:14.737Z'),
		},
		{
			id: 'mihLSrs3HlicniY40',
			fromUserId: '1',
			toUserId: '9',
			permissions: ['read_posts', 'read_messages', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-27T21:44:09.903Z'),
		},
		{
			id: 'kjYcvnzraRBEkhzEY',
			fromUserId: '9',
			toUserId: '1',
			permissions: [
				'read_posts',
				'write_posts',
				'write_messages',
				'read_profile',
				'write_profile',
			],
			status: 'pending',
			createdAt: new Date('2024-09-25T12:52:48.708Z'),
		},
		{
			id: 'k33nMsRJ1jWKUlCKP',
			fromUserId: '3',
			toUserId: '1',
			permissions: ['write_posts', 'write_messages', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-15T18:30:48.891Z'),
		},
		{
			id: 'rJBj6tdJEyKNnUFRs',
			fromUserId: '8',
			toUserId: '1',
			permissions: ['write_posts', 'read_messages'],
			status: 'pending',
			createdAt: new Date('2024-09-19T09:28:36.547Z'),
		},
		{
			id: 'psV0u05aDUXHFDTDc',
			fromUserId: '15',
			toUserId: '4',
			permissions: ['read_posts', 'write_posts', 'read_messages', 'write_messages'],
			status: 'declined',
			createdAt: new Date('2024-09-14T08:01:06.726Z'),
		},
		{
			id: 'woczUfwDC0FXpDVHX',
			fromUserId: '6',
			toUserId: '4',
			permissions: ['write_messages', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-10-02T12:38:37.714Z'),
		},
		{
			id: 'wbE1cvVu8mqWsyGCz',
			fromUserId: '14',
			toUserId: '11',
			permissions: ['write_posts', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-20T16:01:14.393Z'),
		},
		{
			id: 'ulF2TjcMnrnK5je71',
			fromUserId: '15',
			toUserId: '9',
			permissions: ['write_posts', 'read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-29T19:40:29.111Z'),
		},
		{
			id: '1XxDBLSEk1QYG3WO2',
			fromUserId: '10',
			toUserId: '8',
			permissions: [
				'read_posts',
				'write_posts',
				'read_messages',
				'write_messages',
				'read_profile',
				'write_profile',
			],
			status: 'declined',
			createdAt: new Date('2024-09-10T09:03:55.418Z'),
		},
		{
			id: 'nBJ7z5FwpOxR0y3l9',
			fromUserId: '2',
			toUserId: '3',
			permissions: ['read_posts', 'write_posts', 'read_messages'],
			status: 'accepted',
			createdAt: new Date('2024-09-25T19:39:17.707Z'),
		},
		{
			id: 'pkuUYb9FgFM25barZ',
			fromUserId: '7',
			toUserId: '8',
			permissions: ['read_posts', 'write_posts'],
			status: 'pending',
			createdAt: new Date('2024-09-09T00:13:37.119Z'),
		},
		{
			id: 'nplRs4DpNVwAwtGOH',
			fromUserId: '15',
			toUserId: '3',
			permissions: ['read_messages', 'read_profile', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-27T08:56:09.572Z'),
		},
		{
			id: 'j45UG3l1irREMCh9R',
			fromUserId: '2',
			toUserId: '13',
			permissions: ['write_posts', 'read_messages', 'read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-18T13:00:40.275Z'),
		},
		{
			id: 'm8OkcRr6bKVIddYIq',
			fromUserId: '3',
			toUserId: '1',
			permissions: ['read_posts', 'write_posts', 'write_messages', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-13T15:08:57.499Z'),
		},
		{
			id: 'mVTNj3xmCltsy49y0',
			fromUserId: '8',
			toUserId: '3',
			permissions: ['read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-11T09:19:57.448Z'),
		},
		{
			id: 'pvKOCuUnriRCzsWzN',
			fromUserId: '1',
			toUserId: '12',
			permissions: ['write_posts', 'write_messages'],
			status: 'accepted',
			createdAt: new Date('2024-09-21T06:06:25.243Z'),
		},
		{
			id: '597JVPpRpseRyzGds',
			fromUserId: '11',
			toUserId: '3',
			permissions: ['read_messages', 'write_messages', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-26T00:44:15.252Z'),
		},
		{
			id: 'nZWwGXL9atWkA2JLU',
			fromUserId: '15',
			toUserId: '2',
			permissions: ['read_posts', 'write_posts', 'write_messages'],
			status: 'declined',
			createdAt: new Date('2024-09-14T19:34:53.580Z'),
		},
		{
			id: '57oQ2u2hPo2f6h9s8',
			fromUserId: '15',
			toUserId: '9',
			permissions: [
				'write_posts',
				'read_messages',
				'write_messages',
				'read_profile',
				'write_profile',
			],
			status: 'accepted',
			createdAt: new Date('2024-09-13T07:46:47.386Z'),
		},
		{
			id: '5lqeRX9XcjLZ7psGW',
			fromUserId: '7',
			toUserId: '6',
			permissions: ['read_posts', 'read_messages', 'read_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-15T18:46:14.035Z'),
		},
		{
			id: 'jvC13AlaWXjaZiqiW',
			fromUserId: '4',
			toUserId: '2',
			permissions: ['read_posts', 'write_messages', 'read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-20T06:30:10.922Z'),
		},
		{
			id: 'u58BwsNjDM7x3JdQT',
			fromUserId: '10',
			toUserId: '2',
			permissions: ['read_profile', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-13T16:20:10.425Z'),
		},
		{
			id: '1vihQZM6h3lXT0dPI',
			fromUserId: '2',
			toUserId: '5',
			permissions: ['write_messages', 'read_profile', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-18T02:17:20.754Z'),
		},
		{
			id: 'nTL9ONcmkiw0r1WYg',
			fromUserId: '2',
			toUserId: '7',
			permissions: ['read_posts', 'read_profile', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-19T11:01:24.049Z'),
		},
		{
			id: 'uCNLW47snytn2zlZi',
			fromUserId: '4',
			toUserId: '8',
			permissions: ['read_messages', 'write_messages', 'read_profile', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-06T00:00:17.711Z'),
		},
		{
			id: 'wBoaHbw6plZIKnb44',
			fromUserId: '10',
			toUserId: '1',
			permissions: ['read_messages', 'write_messages', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-09T10:30:11.622Z'),
		},
		{
			id: 'jqGyEsLDKJFI0QpaM',
			fromUserId: '9',
			toUserId: '8',
			permissions: ['read_posts', 'write_posts', 'write_messages', 'read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-08T20:52:40.396Z'),
		},
		{
			id: '5iLMvrfmthkoHtRxv',
			fromUserId: '8',
			toUserId: '13',
			permissions: ['read_messages', 'read_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-06T13:57:18.777Z'),
		},
		{
			id: 'j5bEwy3AF0LZXiOPf',
			fromUserId: '7',
			toUserId: '10',
			permissions: ['read_posts', 'write_posts', 'read_messages'],
			status: 'declined',
			createdAt: new Date('2024-09-22T22:58:18.949Z'),
		},
		{
			id: 'n4E3796odu5GuM3ip',
			fromUserId: '8',
			toUserId: '13',
			permissions: ['read_messages', 'write_messages', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-14T22:42:51.683Z'),
		},
		{
			id: '1Ijfq67pzG5HaMJiG',
			fromUserId: '7',
			toUserId: '10',
			permissions: ['write_posts', 'read_profile', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-28T07:48:12.643Z'),
		},
		{
			id: 'pGhJhzQpqXwx0Gf1n',
			fromUserId: '7',
			toUserId: '14',
			permissions: ['write_posts', 'write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-10T01:04:50.012Z'),
		},
		{
			id: '1CpW2xsaRrrFLBn7e',
			fromUserId: '5',
			toUserId: '14',
			permissions: ['read_profile', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-10T02:10:34.932Z'),
		},
		{
			id: 'jFguOFDu76Dbrxmb5',
			fromUserId: '3',
			toUserId: '6',
			permissions: ['read_posts', 'write_messages', 'read_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-27T01:52:05.072Z'),
		},
		{
			id: 'w1ljwZnEdcroi5KAZ',
			fromUserId: '12',
			toUserId: '14',
			permissions: ['write_posts'],
			status: 'accepted',
			createdAt: new Date('2024-09-13T17:27:02.892Z'),
		},
		{
			id: 'jzFx4baDuh7Tgsida',
			fromUserId: '6',
			toUserId: '12',
			permissions: ['write_profile'],
			status: 'accepted',
			createdAt: new Date('2024-09-24T11:02:11.451Z'),
		},
		{
			id: '5dkwq3GA4QbYiK3sv',
			fromUserId: '12',
			toUserId: '9',
			permissions: ['write_posts', 'read_messages'],
			status: 'accepted',
			createdAt: new Date('2024-09-27T19:22:11.137Z'),
		},
		{
			id: '1qHjtGJ1iJJD0wkF6',
			fromUserId: '1',
			toUserId: '12',
			permissions: ['read_messages', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-29T11:07:06.557Z'),
		},
		{
			id: '5zmDdUfjIIfH5MeL3',
			fromUserId: '12',
			toUserId: '13',
			permissions: ['read_posts', 'write_messages', 'read_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-05T14:35:27.330Z'),
		},
		{
			id: 'wRdgIoP6WC1QIX8Ha',
			fromUserId: '11',
			toUserId: '3',
			permissions: ['read_posts', 'read_profile', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-24T23:56:47.479Z'),
		},
		{
			id: 'nVY8D7wdtTqJLQlRL',
			fromUserId: '6',
			toUserId: '5',
			permissions: ['read_posts', 'write_posts', 'write_messages'],
			status: 'accepted',
			createdAt: new Date('2024-09-13T05:49:33.976Z'),
		},
		{
			id: 'pvuyE22B2ImpShueZ',
			fromUserId: '8',
			toUserId: '15',
			permissions: ['read_messages', 'read_profile', 'write_profile'],
			status: 'declined',
			createdAt: new Date('2024-09-06T14:49:47.841Z'),
		},
		{
			id: 'usP7zyN0vB4VfcC77',
			fromUserId: '2',
			toUserId: '5',
			permissions: ['write_posts', 'read_messages', 'write_messages'],
			status: 'pending',
			createdAt: new Date('2024-09-16T22:03:54.907Z'),
		},
		{
			id: 'j8fp3uX7LESGAD8vb',
			fromUserId: '5',
			toUserId: '9',
			permissions: ['read_messages', 'write_messages', 'read_profile', 'write_profile'],
			status: 'pending',
			createdAt: new Date('2024-09-29T17:49:13.296Z'),
		},
	],
};

export const db = await JSONFilePreset<Data>('db.json', defaultData);
